### PR TITLE
support trojan url

### PR DESCRIPTION
**Pull request by timelessg**
support trojan url

### CODE REVIEW

**Comment by timelessg** [comment]
just add support for trojan url
like this https://github.com/trojan-gfw/trojan-url

**Comment by JimLee1996** [comment]
Thanks a lot.

Have you tried to build it and test this function on your mac?

**Comment by timelessg** [comment]
yep,but i found a old bug that sometime when i change server (input manually or import from pasteboard) and do SyncSSLocal(), this dont work anymore. i must restart trojan manually

**Comment by timelessg** [comment]
i try to set the interval of StopSSLocal() and StartSSLocal().it's work for me

**Comment by JimLee1996** [comment]
LGTM! Really appreciate for your works.

**Pull request merged**
